export const ACTION_RECEIVE_NAME_FOLDER = 'ACTION_RECEIVE_NAME_FOLDER';
export const ACTION_OPEN_WINDOW_TO_CREATE = 'ACTION_OPEN_WINDOW_TO_CREATE';
export const ACTION_CLOSED_WINDOW = 'ACTION_CLOSED_WINDOW';
export const ACTION_RECEIVE_CAPTION_NOTE = 'ACTION_RECEIVE_CAPTION_NOTE';